version: '3.9'

services:
  postgres:
    image: postgres
    restart: always
    container_name: postgres
    env_file:
      - '.env'
    ports:
      - '5432:${POSTGRES_PORT}'
    volumes:
      - './db/init.sql:/docker-entrypoint-initdb.d/create_tables.sql'
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "postgres" ]
    networks:
      net:
        ipv4_address: '${POSTGRES_HOST}'

  redis:
    image: redis
    restart: always
    container_name: redis
    env_file:
      - '.env'
    ports:
      - '6379:${REDIS_PORT}'
    healthcheck:
      test: [ "CMD", "redis-cli", "--raw", "incr", "ping" ]
    networks:
      net:
        ipv4_address: '${REDIS_HOST}'

  rabbitmq:
    image: rabbitmq:3-management
    restart: always
    container_name: rabbitmq
    env_file:
      - '.env'
    ports:
      - '5672:5672'
      - '15672:15672'
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "-q", "ping"]
    networks:
      net:
        ipv4_address: '${RABBITMQ_HOST}'

  consumer:
    build: 'consumer/'
    restart: always
    container_name: consumer
    depends_on:
      rabbitmq:
        condition: service_healthy
    networks:
      net:

networks:
  net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.25.0.0/24
